DROP TABLE CUSTOMER;
DROP TABLE PHONE;

CREATE TABLE CUSTOMER
(
  id integer generated by default as identity,
  name varchar(255),
  patronymic varchar(255),
  surname varchar(255),
  phone_id integer,
  primary key (id)
);

CREATE TABLE PHONE
(
  id integer generated by default as identity,
  description varchar(255),
  number varchar(255) not null,
  phoneType varchar(255),
  primary key (id)
);
