DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS PHONE;

CREATE TABLE PHONE
(
  ID          SERIAL PRIMARY KEY,
  description VARCHAR,
  number      VARCHAR NOT NULL UNIQUE,
  phone_type   VARCHAR
);

CREATE TABLE CUSTOMER
(
  ID         SERIAL PRIMARY KEY,
  name       VARCHAR,
  patronymic VARCHAR,
  surname    VARCHAR,
  PHONE_ID   INT REFERENCES PHONE (ID) ON DELETE CASCADE
);



